float64 x                      # x-position [m] in world frame
float64 y                      # y-position [m] in world frame
float64 z                      # z-position [m] in world frame
float64 v_x                   # x-velocity [m/s] in world frame
float64 v_y                   # y-velocity [m/s] in world frame
float64 v_z                   # z-velocity [m/s] in world frame
float64 yaw                   # yaw angle [deg] in world frame
